def raise_exception_msg(message=""):
    print(message)
    raise NameError("ne")